export const EMBEDDED_GOOGLE_FONTS: string[] = [
  'Abril Fatface',
  'Archivo',
  'Assistant',
  'Barlow',
  'Bebas Neue',
  'Bitter',
  'Cabin',
  'Cardo',
  'Cormorant Garamond',
  'Crimson Text',
  'DM Sans',
  'DM Serif Display',
  'Dosis',
  'EB Garamond',
  'Exo 2',
  'Figtree',
  'Fira Code',
  'Fira Sans',
  'Fraunces',
  'Hind',
  'IBM Plex Mono',
  'IBM Plex Sans',
  'Inconsolata',
  'Inria Serif',
  'Inter',
  'JetBrains Mono',
  'Karla',
  'Lato',
  'Libre Baskerville',
  'Libre Franklin',
  'Literata',
  'Lora',
  'Manrope',
  'Merriweather',
  'Montserrat',
  'Mukta',
  'Nanum Gothic',
  'Noto Sans',
  'Noto Sans Display',
  'Noto Sans Mono',
  'Noto Serif',
  'Noto Serif Display',
  'Nunito',
  'Open Sans',
  'Oswald',
  'Outfit',
  'Playfair Display',
  'Plus Jakarta Sans',
  'Poppins',
  'Prompt',
  'Public Sans',
  'Quicksand',
  'Raleway',
  'Red Hat Display',
  'Roboto',
  'Roboto Condensed',
  'Roboto Flex',
  'Roboto Mono',
  'Roboto Slab',
  'Rubik',
  'Sora',
  'Source Code Pro',
  'Source Sans 3',
  'Space Grotesk',
  'Spectral',
  'Syne',
  'Teko',
  'Titillium Web',
  'Ubuntu',
  'Work Sans',
];
